### ISSUE TITLE
Please add a manage cookies button. And please specify a license so people can use the code.

### ISSUE THREAD

**Issue by mhmatthewhugley** [onza/CookieConsent#14]
By adding a manage cookies button people can go back and click deny, which would make it possible for people to revoke their consent.

Githubs projects without licenses are by default all rights reserved which means no one can legally use this code until a license is defined.

**Comment by onza** [comment]
The Manage Cookie Settings button is already integrated (bottom right, half hidden. But that can also be made nicer).

The license (MIT) is now created, thanks for the tip.
